source = ~/.cache/hue/hyprlock-colors.conf

background {
    monitor =
    path = screenshot

    blur_passes = 3
    blur_size = 8
}

general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

input-field {
    monitor =

    size = 250, 60

    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true

    outer_color = rgba(0,0,0,0)
    inner_color = rgba(0,0,0,0.25)

    font_color = $color7

    fade_on_empty = false

    rounding = 12

    check_color = $primary

    placeholder_text = Senha...

    hide_input = false

    position = 0, -200
    halign = center
    valign = center

    font_family = JetBrains Mono
}

label {
    monitor =

    text = cmd[update:1000] date +"%A, %d %B"

    color = $color2

    font_size = 22
    font_family = JetBrains Mono SemiBold

    position = 0, 300

    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:1000] date +"%H:%M"

    color = $foreground

    font_size = 95
    font_family = JetBrains Mono ExtraBold

    position = 0, 200

    halign = center
    valign = center
}

label {
    monitor =

    text = $USER

    color = $foreground

    font_size = 18
    font_family = JetBrains Mono

    position = 0, 120

    halign = center
    valign = center
}
