-- Generated by huectl — do not edit manually
-- XMonad color definitions. Import in xmonad.hs:
--   import Colors (myColors)

module Colors where

-- Special
myBackground :: String
myBackground = "{{background}}"

myForeground :: String
myForeground = "{{foreground}}"

myCursor :: String
myCursor = "{{cursor}}"

-- Normal colors
color0, color1, color2, color3, color4, color5, color6, color7 :: String
color0 = "{{color0}}"
color1 = "{{color1}}"
color2 = "{{color2}}"
color3 = "{{color3}}"
color4 = "{{color4}}"
color5 = "{{color5}}"
color6 = "{{color6}}"
color7 = "{{color7}}"

-- Bright colors
color8, color9, color10, color11, color12, color13, color14, color15 :: String
color8  = "{{color8}}"
color9  = "{{color9}}"
color10 = "{{color10}}"
color11 = "{{color11}}"
color12 = "{{color12}}"
color13 = "{{color13}}"
color14 = "{{color14}}"
color15 = "{{color15}}"

-- Convenience aliases
myBorderColor, myFocusedBorderColor :: String
myBorderColor        = color8
myFocusedBorderColor = color4
