/* Generated by huectl — do not edit manually */
/* Template for midnight (tokyo night) discord theme */

/**
 * @name huectl
 * @description a dark, customizable discord theme. 
 * @author allm
 * @version 2.1.1
 * @invite nz87hXyvcy
 * @website https://github.com/refact0r/midnight-discord
 * @source https://github.com/refact0r/midnight-discord/blob/master/themes/flavors/midnight-tokyo-night.theme.css
 * @authorId 508863359777505290
 * @authorLink https://www.refact0r.dev
*/

/* import theme modules */
@import url('https://refact0r.github.io/midnight-discord/build/midnight.css');

body {
    --font: 'figtree';
    --code-font: '';
    font-weight: 400;

    --gap: 12px;
    --divider-thickness: 4px;
    --border-thickness: 1px;

    --animations: on;
    --list-item-transition: 0.2s ease;
    --dms-icon-svg-transition: 0.4s ease;
    --border-hover-transition: 0.2s ease;

    --top-bar-height: var(--gap);
    --top-bar-button-position: titlebar;
    --top-bar-title-position: off;
    --subtle-top-bar-title: off;

    --custom-window-controls: on;
    --window-control-size: 14px;

    --custom-dms-icon: custom;
    --dms-icon-svg-url: url('https://refact0r.github.io/midnight-discord/assets/Font_Awesome_5_solid_moon.svg');
    --dms-icon-svg-size: 90%;
    --dms-icon-color-before: var(--icon-subtle);
    --dms-icon-color-after: var(--white);
    --custom-dms-background: off;
    --dms-background-image-url: url('');
    --dms-background-image-size: cover;
    --dms-background-color: linear-gradient(70deg, var(--blue-2), var(--purple-2), var(--red-2));

    --background-image: off;
    --background-image-url: url('');

    --transparency-tweaks: off;
    --remove-bg-layer: off;
    --panel-blur: off;
    --blur-amount: 12px;
    --bg-floating: var(--bg-3);

    --custom-chatbar: off;
    --chatbar-height: 47px;

    --small-user-panel: on;
}

/* color options */
:root {
    --colors: on;

    /* text colors */
    --text-0: var(--bg-3);
    --text-1: {{foreground}};
    --text-2: {{color7}};
    --text-3: {{color15}};
    --text-4: {{color8}};
    --text-5: {{color0}};

    /* background and dark colors */
    --bg-1: {{color8}};
    --bg-2: {{color0}};
    --bg-3: {{color0}};
    --bg-4: {{background}};
    --hover: hsla(from {{color4}} h s calc(l * 0.41) / 0.125);
    --active: hsla(from {{color4}} h s calc(l * 0.41) / 0.267);
    --active-2: hsla(from {{color4}} h s calc(l * 0.41) / 0.333);
    --message-hover: hsla(from {{color0}} h s l / 0.1);

    /* accent colors */
    --accent-1: var(--blue-1);
    --accent-2: var(--blue-2);
    --accent-3: var(--blue-3);
    --accent-4: var(--blue-4);
    --accent-5: var(--blue-5);
    --accent-new: var(--accent-2);
    --mention: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 90%) 40%, transparent);
    --mention-hover: linear-gradient(to right, color-mix(in hsl, var(--accent-2), transparent 95%) 40%, transparent);
    --reply: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 90%) 40%, transparent);
    --reply-hover: linear-gradient(to right, color-mix(in hsl, var(--text-3), transparent 95%) 40%, transparent);

    /* status indicator colors */
    --online: var(--green-2);
    --dnd: var(--red-2);
    --idle: var(--yellow-2);
    --streaming: var(--purple-2);
    --offline: var(--text-4);

    /* border colors */
    --border-light: hsla(from {{color0}} h s l / 0.2);
    --border: hsla(from {{color0}} h s l / 0.3);
    --border-hover: hsla(from {{color0}} h s l / 0.3);
    --button-border: hsla(from {{color0}} h s l / 0);

    /* base colors */
    --red-1: {{color9}};
    --red-2: {{color9}};
    --red-3: {{color1}};
    --red-4: {{color1}};
    --red-5: {{color1}};

    --green-1: {{color10}};
    --green-2: {{color2}};
    --green-3: {{color2}};
    --green-4: {{color2}};
    --green-5: {{color2}};

    --blue-1: {{color12}};
    --blue-2: {{color4}};
    --blue-3: {{color12}};
    --blue-4: {{color4}};
    --blue-5: {{color4}};

    --yellow-1: {{color11}};
    --yellow-2: {{color3}};
    --yellow-3: {{color3}};
    --yellow-4: {{color3}};
    --yellow-5: {{color3}};

    --purple-1: {{color13}};
    --purple-2: {{color5}};
    --purple-3: {{color13}};
    --purple-4: {{color5}};
    --purple-5: {{color5}};
}

.divider__908e2:not(.isUnread__908e2) {
    border-color: var(--bg-2);
}
