set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor'

set -g base-index 1
set -g pane-base-index 1

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Utility bindings

unbind r
bind r source-file ~/.config/tmux/tmux.conf

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind c new-window -c "#{pane_current_path}"
bind | split-window -h
bind - split-window -v

unbind s
bind s run-shell "fish -c tfs"

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


# style

set -g status-position top
set -g status-style 'bg=default fg=white'
set -g status-left-length 100
set -g status-left '#[fg=green,bold]  #S #[fg=white,nobold]| '

set -g window-status-current-format '#[fg=brightblack,bg=green,bold] #I #W #[nobold] ' 
set -g window-status-style 'bg=default,fg=white' 
set -g window-status-format '#I #W '

set -g status-right '#[fg=brightblack bg=green]  #{cpu_percentage}   #{mem_percentage} '
set -g message-style 'bg=default fg=white'

set -g pane-border-style 'fg=brightblack'
set -g pane-active-border-style 'fg=blue'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'